name: uncertainty-quantification
on: push

jobs:
  generate-results:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout simulation data
        uses: actions/checkout@v4
        with: 
          path: 'simulation_data'
          submodules: true
      - name: install prerequisites
        working-directory: simulation_data/util
        run: ./install_prerequisites.sh
      - name: create design of experiment
        working-directory: simulation_data/util
        run: |
          mkdir ../parameters/sampling
          node ./create_doe.js -p ../parameters/parameter_specifications -o ../parameters/sampling/doe.json
      - name: create SSD files as input to simulation
        working-directory: simulation_data/util
        run: |
          mkdir ../system/experiments
          node ./createSsd.js -d ../parameters/sampling/doe.json -i ../system/baseline/system_structure.ssd -p ../parameters/ssv -o ../system/experiments
      - name: run simulations
        uses: localhorst87/run-openmcx@v0.3.0
        with:
          ssd: ./simulation_data/system/experiments
          resultDir: ./simulation_data/results/simulation_results
      - name: analyze results
        working-directory: simulation_data/util
        run: |
          mkdir ../results/analyzed
          nExperiments=5
          nRuns=10
          for iExp in $(seq 1 $nExperiments)
          do
            for iRun in $(seq 1 $nRuns)
            do
              node ./analyze_simulation_results.js -r ../results/simulation_results/experiment_${iExp}_run_${iRun}/vehicle_res.csv >> ../results/analyzed/experiment_$iExp.txt
            done
          done
      - name: create P-Boxes of simulation data
        working-directory: simulation_data/util
        run: |
          mkdir ../results/uq
          node ./create_pboxes.js -r ../results/analyzed > ../results/uq/pboxes_simulation.json
      - name: create EDF of real measurement
        working-directory: simulation_data/util
        run: node ./create_pboxes.js -r ../results/real_measurements > ../results/uq/edf_reference.json
      - name: evaluate and add model form uncertainty (area validation metric)
        working-directory: simulation_data/util
        run: node ./evaluate_mfu.js -s ../results/uq/pboxes_simulation.json -m ../results/uq/edf_reference.json          